name: Integración Continua (CI)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Obtener el código del repositorio
      uses: actions/checkout@v4

    - name: Configurar el entorno de Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Ajusta esta versión si usas una diferente
        cache: 'npm'

    - name: Instalar dependencias
      run: npm ci # Es preferible 'npm ci' sobre 'npm install' para servidores automatizados

    - name: Construir el proyecto (Build)
      run: npm run build --if-present
      
    - name: Ejecutar pruebas automatizadas
      run: npm test --if-present
