name: Integración Continua (CI) Java/Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Obtener el código del repositorio
      uses: actions/checkout@v4

    - name: Configurar el entorno de Java (JDK)
      uses: actions/setup-java@v4
      with:
        java-version: '17' # Puedes cambiarlo a '11' o '21' dependiendo de qué versión de Java usaste
        distribution: 'temurin' # Distribución estándar y recomendada de Java
        cache: 'maven' # GitHub cacheará las dependencias de tu pom.xml automáticamente

    - name: Construir y probar el proyecto con Maven
      run: mvn clean install -f AVF2/pom.xml
